export const enum events {
    VIEW_BOX_CHANGE = 'VIEW_BOX_CHANGE',
    CANVAS_CHANGE = 'CANVAS_CHANGE',
    MOUSE_MOVE = 'MOUSE_MOVE',
    MOUSE_CLICK = 'MOUSE_CLICK',
    MOUSE_DRAG_START = 'MOUSE_DRAG_START',
    MOUSE_DRAG = 'MOUSE_DRAG',
    MOUSE_DRAG_END = 'MOUSE_DRAG_END'
}